version: "3.9"

services:
  postgresql:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysupersecretpassword
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    networks:
      - pgnetwork
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgresdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@github.com
      PGADMIN_DEFAULT_PASSWORD: adminspassword
    ports:
      - "8080:80"
    networks:
      - pgnetwork
    depends_on:
      postgresql:
        condition: service_healthy
          
volumes:
  pgdata:

networks:
  pgnetwork:
    driver: bridge
